### ISSUE TITLE
Generalised Bank Interface

### ISSUE THREAD

**Issue by RileyEv** [RileyEv/bank#1]
The bank interface will provide a generalised way to access data across multiple open-banking APIs

```[tasklist]
### Tasks
- [ ] https://github.com/bank-manager/bank-interface/issues/2
- [ ] https://github.com/bank-manager/bank-interface/issues/3
- [ ] https://github.com/bank-manager/bank-interface/issues/4
- [ ] https://github.com/bank-manager/bank-interface/issues/5
- [ ] https://github.com/bank-manager/bank-interface/issues/6
```
